import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { Suspense } from 'react';

import { AppShell } from '@/components/app-shell';
import { AttentionEmpty, AttentionList } from '@/components/attention-list';
import { Callout } from '@/components/callout';
import { fetchAttention } from '@/lib/attention';
import { fetchChannels, type ChannelRow } from '@/lib/channels';
import { createClient } from '@/lib/supabase/server';
import { LABEL } from '@/lib/ui';
import { cn } from '@/lib/utils';

export const metadata: Metadata = { title: 'Needs attention · Switchboard' };

/**
 * "Needs attention" (US-9) — Phase 5.
 *
 * ⭐ **This screen is the answer to a question the assistant could not answer**,
 * and that is not a coincidence. ADR-017 measured *"summarise what needs my
 * attention"* and found the model was never shown a single one of the real
 * problems: semantic search returns prose that *sounds* urgent, because
 * importance is not a direction in embedding space. The fix was never a prompt.
 * It was extracting structure on the way in, which is what this reads.
 *
 * ⚠ Every row is a **proposal** (ADR-010). Nothing here has been acted on, and
 * nothing here has touched a calendar.
 */
export default async function AttentionPage() {
  const supabase = await createClient();

  // Checked here as well as in `proxy.ts`: this page renders quoted message
  // content, and it must not do so for an unauthenticated request even if the
  // route gate is ever misconfigured.
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect('/login?next=/attention');

  const channels = fetchChannels(supabase);
  // Not awaited: the shell streams ahead of the queue behind the Suspense
  // boundary below, exactly as the timeline does.
  const attention = fetchAttention(supabase);

  return (
    <AppShell
      title="Needs attention"
      description="Meetings, commitments and requests found in your messages."
      userEmail={user.email ?? 'Signed in'}
      userId={user.id}
      activeHref="/attention"
      channels={channels}
    >
      <Suspense fallback={<QueueSkeleton />}>
        <Queue attention={attention} channels={channels} />
      </Suspense>
    </AppShell>
  );
}

async function Queue({
  attention,
  channels,
}: {
  attention: ReturnType<typeof fetchAttention>;
  channels: Promise<{ channels: ChannelRow[]; error: string | null }>;
}) {
  const [{ items, error }, { channels: rows }] = await Promise.all([attention, channels]);

  if (error) {
    return (
      <Callout tone="error" role="alert">
        Could not load the queue: {error}
      </Callout>
    );
  }

  if (items.length === 0) {
    /*
     * ⚠ Two different empty states, and telling them apart needs a second fact
     * this query does not have: whether extraction has run at all.
     *
     * `message_extraction_runs` holds it, but that table is worker-only and
     * carries no console-facing query — and adding one for a single sentence is
     * more surface than the sentence is worth. So the distinction is drawn from
     * what IS in hand: a console with no channel connected has nothing to read,
     * and a console with a channel has been read and found nothing.
     *
     * That is honest for every state this system can actually be in, because
     * extraction runs automatically on ingest. If it ever becomes possible to
     * have messages that have not been through the pass, this needs the real
     * count — see `AttentionEmpty`.
     */
    return <AttentionEmpty extracted={rows.length > 0} />;
  }

  // ONE instant for the whole page, so the overdue boundary cannot fall between
  // two rows of the same render.
  const now = new Date();
  const overdue = items.filter((item) => {
    const when = item.startsAt ?? item.dueAt;
    return when !== null && new Date(when).getTime() < now.getTime();
  }).length;

  return (
    <div>
      <p className={cn(LABEL, 'mb-3')}>
        {items.length} item{items.length === 1 ? '' : 's'}
        {overdue > 0 && ` · ${overdue} already passed`}
      </p>

      <AttentionList items={items} channels={rows} now={now} />

      {/*
        ⚠ Said out loud, on the screen, rather than assumed.

        Every row here is a model's reading of somebody's mail. The console
        naming the model is the same honesty ADR-015 required of summaries —
        "generated by llama-3.1-8b-instant" is a more truthful claim than "AI",
        and it is why `extractions.model` is recorded per row (ADR-006).
      */}
      <p className={cn(LABEL, 'mt-4 max-w-[62ch] normal-case')}>
        Each item was read out of a message by{' '}
        <span className="font-mono">{items[0]?.model ?? 'a model'}</span> and quotes the
        sentence it came from. Nothing here has been added to your calendar.
      </p>
    </div>
  );
}

/** Matches the shape of a loaded row so the page does not jump when it lands. */
function QueueSkeleton() {
  return (
    <div className="border-t border-border" aria-hidden>
      {[0, 1, 2].map((i) => (
        <div key={i} className="border-b border-border py-4">
          <div className="h-2.5 w-24 rounded bg-faint" />
          <div className="mt-2 h-3 w-2/3 rounded bg-faint" />
          <div className="mt-2 h-2.5 w-1/2 rounded bg-faint" />
        </div>
      ))}
    </div>
  );
}
